name: Publish Kotlin docs

permissions: write-all

on: [push]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to get all tags for versioning

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate Kotlin documentation
        run: python3 ProcessDocs/ProcessKotlinDocs/process_docs.py --input-dir SourceDocs/KotlinDocs/html --output-dir out --menu-file toc.html --stylesheet style.css --log-file log.txt

      - name: Generate table of contents
        run: python3 ProcessDocs/ProcessKotlinDocs/build_toc.py SourceDocs/KotlinDocs/html/HelpTOC.json out/toc.html  out/toc.css out/toc_script.js

      - name: Zip up processed Kotlin docs
        run: zip -r kotlin_docs.zip out

      - name: Get tag name
        id: get_tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: kotlin_docs.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}